apiVersion: v1
kind: Service
metadata:
  name: kdc
  labels:
    component: kdc
spec:
  type: NodePort
  ports:
    - port: 88
      targetPort: kdc-tcp
      protocol: TCP
      name: kdc-tcp
    - port: 88
      targetPort: kdc-udp
      protocol: UDP
      name: kdc-udp
  selector:
    component: kdc