apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kerberos-db
  labels:
    component: kdc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi