apiVersion: v1
kind: ConfigMap
metadata:
  name: krb5-config
  labels:
    component: krb5
data:
  krb5.conf: |-
    [logging]
     default = CONSOLE
     kdc = CONSOLE
     admin_server = CONSOLE

    [libdefaults]
     default_realm = FOO.COM
     dns_lookup_realm = false
     dns_lookup_kdc = true
     rdns = false
     ticket_lifetime = 24h
     forwardable = true
     udp_preference_limit = 0
     default_ccache_name = /tmp/krb5kdc_%{uid}
     permitted_enctypes = aes256-cts-hmac-sha1-96 aes256-cts-hmac-sha384-192 camellia256-cts-cmac aes128-cts-hmac-sha1-96 aes128-cts-hmac-sha256-128 camellia128-cts-cmac

    [realms]
     FOO.COM = {
      kdc = kdc.default.svc.cluster.local:88
      master_kdc = kdc.default.svc.cluster.local:88
      admin_server = kadmin.default.svc.cluster.local:749
      default_domain = cluster.local
     ; pkinit_anchors = FILE:/path/to/kdc-ca-bundle.pem
     ; pkinit_pool = FILE:/path/to/ca-bundle.pem
     }

    [domain_realm]
     .cluster.local = FOO.COM
     foo.com = FOO.COM